"""CLI для Voyage Framework.

Команды:
    voyage init          — инициализировать проект
    voyage status        — статус проекта
    voyage run <role>    — запустить агента с ролью
    voyage task <role> <task> — сгенерировать TASK.md
    voyage events        — показать последние события
    voyage approve       — показать pending approval запросы
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING

from voyage_framework.agents.runtime import AgentRuntime
from voyage_framework.chronicler.decision_log import DecisionLog
from voyage_framework.chronicler.docs_builder import DocsBuilder
from voyage_framework.chronicler.journal import ProcessJournal
from voyage_framework.core.event_engine import EventEngine
from voyage_framework.core.models import SecurityPolicy
from voyage_framework.core.task_engine import (
    TaskAlreadyExistsError,
    TaskEngine,
    TaskNotFoundError,
    TaskTransitionError,
)
from voyage_framework.core.task_parser import TaskParser, TaskValidationError
from voyage_framework.security.policy import PolicyEnforcer
from voyage_framework.security.sandbox import SecureExecutor
from voyage_framework.specs.task_generator import TaskGenerator

if TYPE_CHECKING:
    from voyage_framework.core.context_builder import ContextBuilder


def _docs_engine_and_builder(
    args: argparse.Namespace,
) -> tuple[EventEngine, ProcessJournal, DecisionLog, DocsBuilder]:
    """Создать EventEngine, ProcessJournal, DecisionLog и DocsBuilder."""
    engine = EventEngine()
    journal = ProcessJournal(
        engine,
        project_id=getattr(args, "project", "default") or "default",
    )
    decision_log = DecisionLog(engine)
    builder = DocsBuilder(journal, decision_log)
    return engine, journal, decision_log, builder


def docs_build(args: argparse.Namespace) -> int:
    """Собрать всю документацию в docs/."""
    _, _, _, builder = _docs_engine_and_builder(args)
    output_dir = Path(args.output) if args.output else Path("docs")
    builder.build_all(
        project_id=getattr(args, "project", "default") or "default",
        output_dir=output_dir,
    )
    print(f"📚 Documentation built in {output_dir.absolute()}")
    return 0


def docs_tutorial(args: argparse.Namespace) -> int:
    """Сгенерировать один tutorial-файл."""
    _, _, _, builder = _docs_engine_and_builder(args)
    output_dir = Path(args.output) if args.output else Path("docs")
    path = builder.build_tutorial(args.correlation_id, output_dir=output_dir)
    print(f"📖 Tutorial saved to {path.absolute()}")
    return 0


def docs_example(args: argparse.Namespace) -> int:
    """Сгенерировать example-директорию."""
    _, _, _, builder = _docs_engine_and_builder(args)
    output_dir = Path(args.output) if args.output else Path("docs/examples")
    path = builder.generator.save_example(
        args.correlation_id,
        args.name,
        output_dir,
    )
    print(f"📂 Example saved to {path.absolute()}")
    return 0


def docs_serve(args: argparse.Namespace) -> int:
    """Запустить локальный сервер для docs/."""
    import subprocess

    docs_dir = Path(args.dir) if args.dir else Path("docs")
    if not docs_dir.exists():
        print(f"❌ Directory not found: {docs_dir.absolute()}")
        return 1
    print(f"🌐 Serving docs at http://localhost:{args.port}")
    print("   Press Ctrl+C to stop")
    try:
        subprocess.run(
            [sys.executable, "-m", "http.server", str(args.port)],
            cwd=docs_dir,
            check=True,
        )
    except KeyboardInterrupt:
        print("\n👋 Server stopped")
    except FileNotFoundError:
        print("❌ Could not start http.server")
        return 1
    return 0


def init_project(args: argparse.Namespace) -> int:
    """Инициализировать проект Voyage."""
    project_dir = Path(args.dir)
    voyage_dir = project_dir / ".voyage"
    voyage_dir.mkdir(parents=True, exist_ok=True)

    # Создать базовые файлы
    (voyage_dir / "events.db").touch()
    (voyage_dir / "events.jsonl").touch()
    (voyage_dir / "audit.jsonl").touch()

    # README
    readme = project_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            """# Voyage Project

Generated by Voyage Framework v4.0

## Quick Start

```bash
voyage run developer --task "Implement feature X"
voyage task developer --task "Refactor module Y"
```
""",
            encoding="utf-8",
        )

    print(f"✅ Project initialized in {project_dir.absolute()}")
    print(f"   Events DB: {voyage_dir / 'events.db'}")
    print(f"   Audit Log: {voyage_dir / 'audit.jsonl'}")
    return 0


def show_status(args: argparse.Namespace) -> int:
    """Показать статус проекта."""
    engine = EventEngine()
    count = engine.count()
    print(f"📊 Total events: {count}")

    # Последние события
    events = engine.get_events(limit=5)
    if events:
        print("\n📝 Last events:")
        for ev in events:
            ts = ev.timestamp.strftime("%H:%M:%S")
            print(f"   [{ts}] {ev.event_type.value} | {ev.project_id}")
    else:
        print("\n📝 No events yet. Run 'voyage run' to start.")

    return 0


async def run_agent(args: argparse.Namespace) -> int:
    """Запустить агента."""
    engine = EventEngine()
    policy = PolicyEnforcer()
    security = SecurityPolicy()
    if args.backend == "docker":
        from voyage_framework.security.docker_backend import DockerBackend

        executor = SecureExecutor(
            security,
            project_root=Path.cwd(),
            backend=DockerBackend(project_root=Path.cwd(), image=args.docker_image),
        )
    else:
        executor = SecureExecutor(security, project_root=Path.cwd())
    runtime = AgentRuntime(engine, executor, policy)

    role = args.role
    task = args.task or "No task specified"
    plan = args.plan.split(";") if args.plan else [task]

    print(f"🚀 Starting agent: role={role}, task={task}")
    result = await runtime.run(
        role=role,
        task=task,
        plan=plan,
        project_id=args.project or "default",
    )

    if result.success:
        print(f"✅ Agent completed. Confidence: {result.state.confidence:.2f}")
    else:
        print(f"❌ Agent failed. Status: {result.state.status.value}")
        if result.output.get("error"):
            print(f"   Error: {result.output['error']}")

    return 0 if result.success else 1


def generate_task(args: argparse.Namespace) -> int:
    """Сгенерировать TASK.md + CONTEXT.json."""
    engine = EventEngine()
    generator = TaskGenerator(engine)

    spec = generator.generate(
        role=args.role,
        task=args.task,
        micro_phase=args.phase,
        project_id=args.project or "default",
    )

    task_path, context_path = generator.write_task_files(spec)

    print("✅ Task generated:")
    print(f"   TASK.md:      {task_path.absolute()}")
    print(f"   CONTEXT.json: {context_path.absolute()}")
    print(f"   Task ID:      {spec.task_id}")
    return 0


def show_events(args: argparse.Namespace) -> int:
    """Показать события."""
    engine = EventEngine()
    events = engine.get_events(
        project_id=args.project,
        limit=args.limit,
    )

    print(f"📊 Events (limit={args.limit}):")
    for ev in events:
        ts = ev.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        print(f"   {ev.event_id[:8]} | {ev.event_type.value:25} | {ts} | {ev.project_id}")

    return 0


def show_approvals(args: argparse.Namespace) -> int:
    """Показать pending approval запросы."""
    from voyage_framework.security.approval import ApprovalQueue

    queue = ApprovalQueue()
    queue.cleanup_expired()
    pending = queue.get_pending()

    if not pending:
        print("✅ No pending approvals")
        return 0

    print(f"⏳ Pending approvals ({len(pending)}):")
    for req in pending:
        ts = req.timestamp.strftime("%H:%M:%S")
        cmd = " ".join(req.command[:3])
        print(f"   {req.request_id[:8]} | {cmd}... | {req.role} | {ts}")

    return 0


def evaluate_project(args: argparse.Namespace) -> int:
    """Показать evaluation summary проекта."""
    from voyage_framework.core.event_engine import EventEngine
    from voyage_framework.improvement.evaluator import Evaluator
    from voyage_framework.improvement.feedback_loop import FeedbackLoop
    from voyage_framework.improvement.golden_dataset import GoldenDataset
    from voyage_framework.improvement.rule_engine import RuleEngine

    engine = EventEngine()
    evaluator = Evaluator(project_root=Path(args.dir))
    rule_engine = RuleEngine(engine=engine)
    golden_dataset = GoldenDataset(engine=engine)
    feedback = FeedbackLoop(engine, evaluator, rule_engine, golden_dataset)

    summary = feedback.get_improvement_summary(project_id=args.project)

    print(f"📊 Improvement summary for project '{args.project}':")
    print(f"   Evaluations: {summary['evaluations_count']}")
    print(f"   Rules suggested: {summary['rules_suggested_count']}")
    print(f"   Golden matches: {summary['golden_matches_count']}")
    print(f"   Average score: {summary['average_score']:.2f}")
    print(f"   Last score: {summary['last_score']}")
    print(f"   Stored rules: {summary['stored_rules_count']}")
    print(f"   Golden solutions: {summary['golden_solutions_count']}")

    return 0


def graph_visualize(args: argparse.Namespace) -> int:
    """Визуализировать граф workflow."""
    from voyage_framework.agents.langgraph_runtime import LangGraphRuntime
    from voyage_framework.core.event_engine import EventEngine
    from voyage_framework.security.policy import PolicyEnforcer
    from voyage_framework.security.sandbox import SecureExecutor

    engine = EventEngine()
    policy = PolicyEnforcer()
    executor = SecureExecutor(SecurityPolicy(), project_root=Path.cwd())
    runtime = LangGraphRuntime(engine, executor, policy)

    mermaid = runtime.visualize()
    print(mermaid)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(mermaid, encoding="utf-8")
    print(f"📝 Graph saved to {output_path.absolute()}")
    return 0


async def graph_run(args: argparse.Namespace) -> int:
    """Запустить агента через LangGraphRuntime."""
    from voyage_framework.agents.langgraph_runtime import LangGraphRuntime
    from voyage_framework.core.event_engine import EventEngine
    from voyage_framework.improvement.evaluator import Evaluator
    from voyage_framework.improvement.feedback_loop import FeedbackLoop
    from voyage_framework.improvement.golden_dataset import GoldenDataset
    from voyage_framework.improvement.rule_engine import RuleEngine
    from voyage_framework.security.docker_backend import DockerBackend
    from voyage_framework.security.policy import PolicyEnforcer
    from voyage_framework.security.sandbox import SecureExecutor

    engine = EventEngine()
    policy = PolicyEnforcer()
    security = SecurityPolicy()
    if args.backend == "docker":
        executor = SecureExecutor(
            security,
            project_root=Path.cwd(),
            backend=DockerBackend(project_root=Path.cwd(), image=args.docker_image),
        )
    else:
        executor = SecureExecutor(security, project_root=Path.cwd())

    feedback_loop = None
    if args.feedback:
        evaluator = Evaluator(project_root=Path.cwd())
        rule_engine = RuleEngine(engine=engine)
        golden = GoldenDataset(engine=engine)
        feedback_loop = FeedbackLoop(engine, evaluator, rule_engine, golden)

    runtime = LangGraphRuntime(engine, executor, policy, feedback_loop=feedback_loop)
    plan = args.plan.split(";") if args.plan else [args.task]

    result = await runtime.run(
        role=args.role,
        task=args.task,
        plan=plan,
        project_id=args.project or "default",
        correlation_id=args.correlation_id,
    )

    if result.success:
        print(f"✅ Graph completed. Confidence: {result.state.confidence:.2f}")
    else:
        print(f"❌ Graph failed. Status: {result.output.get('status')}")
        if result.output.get("error"):
            print(f"   Error: {result.output['error']}")

    return 0 if result.success else 1


def graph_state(args: argparse.Namespace) -> int:
    """Показать последний сохранённый state по correlation_id."""
    from voyage_framework.agents.langgraph_runtime import LangGraphRuntime
    from voyage_framework.core.event_engine import EventEngine
    from voyage_framework.security.policy import PolicyEnforcer
    from voyage_framework.security.sandbox import SecureExecutor

    engine = EventEngine()
    policy = PolicyEnforcer()
    executor = SecureExecutor(SecurityPolicy(), project_root=Path.cwd())
    runtime = LangGraphRuntime(engine, executor, policy)

    state = runtime.get_state(args.correlation_id)
    if state is None:
        print(f"❌ No state found for correlation_id={args.correlation_id}")
        return 1

    print(f"📊 State for correlation_id={args.correlation_id}:")
    for key, value in state.model_dump().items():
        print(f"   {key}: {value}")
    return 0


def chronicler_journal(args: argparse.Namespace) -> int:
    """Показать последние шаги из ProcessJournal."""
    from voyage_framework.chronicler.journal import ProcessJournal
    from voyage_framework.core.event_engine import EventEngine

    engine = EventEngine()
    journal = ProcessJournal(
        engine,
        project_id=args.project or "default",
        correlation_id=args.correlation_id,
    )
    steps = journal.get_steps(
        correlation_id=args.correlation_id,
        step_type=args.step_type,
        limit=args.limit,
    )

    if not steps:
        print("📝 No steps found")
        return 0

    print(f"📝 Steps (limit={args.limit}):")
    for event in steps:
        payload = event.payload
        print(
            f"   {payload.get('step_type', 'unknown'):10} | {payload.get('description', '')[:60]}"
        )
    return 0


def chronicler_replay(args: argparse.Namespace) -> int:
    """Сгенерировать replay-скрипт для correlation_id."""
    from voyage_framework.chronicler.journal import ProcessJournal
    from voyage_framework.chronicler.replay import ReplayGenerator
    from voyage_framework.core.event_engine import EventEngine

    engine = EventEngine()
    journal = ProcessJournal(
        engine,
        project_id=args.project or "default",
        correlation_id=args.correlation_id,
    )
    generator = ReplayGenerator(journal)
    path = generator.save_script(args.correlation_id, path=args.output)
    print(f"🎬 Replay script saved to {path.absolute()}")
    return 0


def chronicler_decisions(args: argparse.Namespace) -> int:
    """Показать decision log."""
    from voyage_framework.chronicler.decision_log import DecisionLog
    from voyage_framework.core.event_engine import EventEngine

    engine = EventEngine()
    decision_log = DecisionLog(engine)
    decisions = decision_log.get_decisions(project_id=args.project or "default")

    if not decisions:
        print("🧠 No decisions recorded")
        return 0

    print(f"🧠 Decisions ({len(decisions)}):")
    for event in decisions:
        payload = event.payload
        print(f"   {payload.get('context', '')}: {payload.get('chosen', '')}")
        print(f"      {payload.get('rationale', '')[:80]}")
    return 0


def chronicler_tutorial(args: argparse.Namespace) -> int:
    """Сгенерировать tutorial draft для correlation_id."""
    from voyage_framework.chronicler.journal import ProcessJournal
    from voyage_framework.chronicler.tutorial_generator import TutorialDraft
    from voyage_framework.core.event_engine import EventEngine

    engine = EventEngine()
    journal = ProcessJournal(
        engine,
        project_id=args.project or "default",
        correlation_id=args.correlation_id,
    )
    draft = TutorialDraft(journal)
    tutorial = draft.generate_draft(args.correlation_id)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(tutorial, encoding="utf-8")
        print(f"📚 Tutorial draft saved to {output_path.absolute()}")
    else:
        print(tutorial)
    return 0


def _dispatch_graph(args: argparse.Namespace) -> int:
    """Диспетчер подкоманд graph."""
    if not args.graph_command:
        print("❌ No graph subcommand provided. Use: visualize, run, state")
        return 1
    if args.graph_command == "visualize":
        return graph_visualize(args)
    if args.graph_command == "run":
        return asyncio.run(graph_run(args))
    if args.graph_command == "state":
        return graph_state(args)
    return 1


def _dispatch_chronicler(args: argparse.Namespace) -> int:
    """Диспетчер подкоманд chronicler."""
    if not args.chronicler_command:
        print("❌ No chronicler subcommand provided. Use: journal, replay, decisions, tutorial")
        return 1
    if args.chronicler_command == "journal":
        return chronicler_journal(args)
    if args.chronicler_command == "replay":
        return chronicler_replay(args)
    if args.chronicler_command == "decisions":
        return chronicler_decisions(args)
    if args.chronicler_command == "tutorial":
        return chronicler_tutorial(args)
    return 1


def _dispatch_docs(args: argparse.Namespace) -> int:
    """Диспетчер подкоманд docs."""
    if not args.docs_command:
        print("❌ No docs subcommand provided. Use: build, tutorial, example, serve")
        return 1
    if args.docs_command == "build":
        return docs_build(args)
    if args.docs_command == "tutorial":
        return docs_tutorial(args)
    if args.docs_command == "example":
        return docs_example(args)
    if args.docs_command == "serve":
        return docs_serve(args)
    return 1


def _get_tasks_db_path(args: argparse.Namespace) -> Path:
    """Получить путь к runtime БД задач."""
    return Path(getattr(args, "tasks_db", ".voyage/tasks.db"))


def _build_task_engine(args: argparse.Namespace) -> TaskEngine:
    """Создать TaskEngine для обычного CLI-вызова."""
    return TaskEngine(db_path=_get_tasks_db_path(args))


def _dispatch_tasks(
    args: argparse.Namespace,
    engine: TaskEngine | None = None,
) -> int:
    """Диспетчер подкоманд tasks (plural, runtime task management)."""
    command = getattr(args, "tasks_command", None)
    if not command:
        print(
            "❌ No tasks subcommand provided. "
            "Use: create, list, show, start, block, unblock, complete, fail, archive"
        )
        return 1

    owns_engine = engine is None
    task_engine = engine or _build_task_engine(args)
    try:
        handlers: dict[str, Callable[[argparse.Namespace, TaskEngine], int]] = {
            "create": _tasks_create,
            "list": _tasks_list,
            "show": _tasks_show,
            "start": _tasks_start,
            "block": _tasks_block,
            "unblock": _tasks_unblock,
            "complete": _tasks_complete,
            "fail": _tasks_fail,
            "archive": _tasks_archive,
        }
        handler = handlers.get(command)
        return handler(args, task_engine) if handler is not None else 1
    finally:
        if owns_engine:
            task_engine.close()


def _tasks_create(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Создать задачу из task.yaml."""
    parser = TaskParser()
    try:
        spec = parser.parse(args.file)
    except (TaskValidationError, FileNotFoundError) as e:
        print(f"❌ Error: {e}")
        return 1

    try:
        record = engine.create_from_spec(spec)
    except TaskAlreadyExistsError as e:
        print(f"❌ Error: {e}")
        return 1

    print(f"✅ Created task {record.id}: {record.title}")
    print(f"   Role: {record.role}")
    print(f"   Status: {record.status}")
    return 0


def _tasks_list(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Показать список задач."""
    records = engine.list(
        status=args.status,
        role=args.role,
        limit=args.limit or 20,
    )

    if not records:
        print("📝 No tasks found")
        return 0

    print(f"📝 Tasks ({len(records)}):")
    print(f"{'ID':12} {'Status':12} {'Role':12} {'Title'}")
    print("-" * 60)
    for r in records:
        short_id = r.id[:10]
        print(f"{short_id:12} {r.status:12} {r.role:12} {r.title[:40]}")
    return 0


def _tasks_show(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Показать детали задачи."""
    record = engine.get(args.task_id)
    if record is None:
        print(f"❌ Error: task {args.task_id} not found")
        return 1

    print(f"📋 Task {record.id}")
    print(f"   Title:       {record.title}")
    print(f"   Status:      {record.status}")
    print(f"   Role:        {record.role}")
    print(f"   Priority:    {record.priority or '—'}")
    print(f"   Mode:        {record.mode or '—'}")
    print(f"   Created:     {record.created_at}")
    if record.started_at:
        print(f"   Started:     {record.started_at}")
    if record.completed_at:
        print(f"   Completed:   {record.completed_at}")
    if record.archived_at:
        print(f"   Archived:    {record.archived_at}")
    print("   Criteria:")
    for c in record.acceptance_criteria:
        print(f"      - {c}")
    if record.description:
        print(f"   Description: {record.description[:100]}")
    return 0


def _tasks_start(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Начать задачу."""
    try:
        record = engine.start(args.task_id)
        print(f"🚀 Started task {record.id} → {record.status}")
        return 0
    except TaskNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except TaskTransitionError as e:
        print(f"❌ Error: {e}")
        return 1


def _tasks_block(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Заблокировать задачу."""
    reason = args.reason or "No reason provided"
    try:
        record = engine.block(args.task_id, reason=reason)
        print(f"⏸️  Blocked task {record.id} → {record.status}")
        return 0
    except TaskNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except TaskTransitionError as e:
        print(f"❌ Error: {e}")
        return 1


def _tasks_unblock(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Разблокировать задачу."""
    try:
        record = engine.unblock(args.task_id)
        print(f"▶️  Unblocked task {record.id} → {record.status}")
        return 0
    except TaskNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except TaskTransitionError as e:
        print(f"❌ Error: {e}")
        return 1


def _tasks_complete(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Завершить задачу."""
    try:
        record = engine.complete(args.task_id)
        print(f"✅ Completed task {record.id} → {record.status}")
        return 0
    except TaskNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except TaskTransitionError as e:
        print(f"❌ Error: {e}")
        return 1


def _tasks_fail(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Отметить задачу как failed."""
    reason = args.reason or "No reason provided"
    try:
        record = engine.fail(args.task_id, reason=reason)
        print(f"❌ Failed task {record.id} → {record.status}")
        return 0
    except TaskNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except TaskTransitionError as e:
        print(f"❌ Error: {e}")
        return 1


def _tasks_archive(args: argparse.Namespace, engine: TaskEngine) -> int:
    """Архивировать задачу."""
    try:
        record = engine.archive(args.task_id)
        print(f"📦 Archived task {record.id} → {record.status}")
        return 0
    except TaskNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except TaskTransitionError as e:
        print(f"❌ Error: {e}")
        return 1


# ───────────────────────────────────────────────────────────────
# Sync commands (Phase 4: Context Builder Lite)
# ───────────────────────────────────────────────────────────────


def _sync_build(
    args: argparse.Namespace,
    builder: ContextBuilder | None = None,
) -> int:
    """Build project context (voyage sync build)."""
    from voyage_framework.core.context_builder import ContextBuilder

    try:
        if builder is None:
            task_engine = _build_task_engine(args)
            builder = ContextBuilder(task_engine)

        files = [Path(f) for f in (args.files or [])]
        output_path = Path(args.output)

        context = builder.build(
            files,
            project_id=getattr(args, "project", "default") or "default",
        )
        builder.write_context(context, output_path)

        print(f"✅ Context built: {len(context.tasks)} tasks")
        print(f"📄 Written to {output_path.absolute()}")
        return 0
    except Exception as e:
        print(f"❌ Error building context: {e}")
        return 1


def _sync_check(
    args: argparse.Namespace,
    builder: ContextBuilder | None = None,
) -> int:
    """Check diffs between YAML and runtime (voyage sync check)."""
    from voyage_framework.core.context_builder import ContextBuilder

    try:
        if builder is None:
            task_engine = _build_task_engine(args)
            builder = ContextBuilder(task_engine)

        files = [Path(f) for f in (args.files or [])]
        diffs = builder.check(files)

        if not diffs:
            print("✅ No diffs found")
            return 0

        for diff in diffs:
            if not diff.changed_fields:
                print(f"✅ {diff.task_id}: in sync")
            else:
                print(f"⚠️  {diff.task_id}: {len(diff.changed_fields)} field(s) changed")
                for field, changes in diff.changed_fields.items():
                    yaml_val = changes.get("yaml")
                    runtime_val = changes.get("runtime")
                    print(f"   {field}: {yaml_val} → {runtime_val}")

            if not diff.exists_in_runtime:
                print(f"   ⚠️  No runtime record for {diff.task_id}")

        return 0
    except Exception as e:
        print(f"❌ Error checking diffs: {e}")
        return 1


def _sync_status(
    args: argparse.Namespace,
    engine: TaskEngine | None = None,
) -> int:
    """Show runtime task status (voyage sync status).

    Reads TaskEngine runtime database, not task.yaml files.
    """
    try:
        if engine is None:
            engine = _build_task_engine(args)

        records = engine.list(limit=1000)
        total = len(records)

        if not records:
            print("✅ No runtime tasks found (empty project)")
            return 0

        # Count by status
        by_status: dict[str, int] = {}
        for r in records:
            by_status[r.status] = by_status.get(r.status, 0) + 1

        print("📊 Sync Status")
        print(f"   Total runtime tasks: {total}")
        print("   By status:")
        for status, count in sorted(by_status.items()):
            print(f"      {status}: {count}")

        # Latest updated task
        latest = max(records, key=lambda r: r.updated_at)
        print(f"   Latest updated: {latest.id} ({latest.title[:40]}) → {latest.status}")
        return 0
    except Exception as e:
        print(f"❌ Error: {e}")
        return 1


def _dispatch_sync(
    args: argparse.Namespace,
    builder: ContextBuilder | None = None,
    engine: TaskEngine | None = None,
) -> int:
    """Dispatcher for sync subcommands."""
    command = getattr(args, "sync_command", None)
    if not command:
        print("❌ No sync subcommand provided. Use: build, check, status")
        return 1

    if command == "build":
        return _sync_build(args, builder=builder)
    elif command == "check":
        return _sync_check(args, builder=builder)
    elif command == "status":
        if engine is None:
            engine = _build_task_engine(args)
        return _sync_status(args, engine=engine)
    else:
        print(f"❌ Unknown sync command: {command}")
        return 1


def main() -> int:
    """Точка входа CLI."""
    # Гарантировать UTF-8 для stdout/stderr на Windows
    if sys.platform == "win32":
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        prog="voyage",
        description="Voyage AI Dev Framework v4.0",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Initialize project")
    init_parser.add_argument("--dir", default=".", help="Project directory")

    # status
    subparsers.add_parser("status", help="Show project status")

    # run
    run_parser = subparsers.add_parser("run", help="Run agent")
    run_parser.add_argument("role", help="Agent role")
    run_parser.add_argument("--task", default="", help="Task description")
    run_parser.add_argument("--plan", default="", help="Execution plan (semicolon-separated)")
    run_parser.add_argument("--project", default="default", help="Project ID")
    run_parser.add_argument(
        "--backend",
        choices=["subprocess", "docker"],
        default="subprocess",
        help="Sandbox backend (default: subprocess)",
    )
    run_parser.add_argument(
        "--docker-image",
        default="python:3.11-slim",
        help="Docker image when --backend=docker",
    )

    # task (singular — generate TASK.md)
    task_parser = subparsers.add_parser("task", help="Generate TASK.md")
    task_parser.add_argument("role", help="Agent role")
    task_parser.add_argument("--task", required=True, help="Task description")
    task_parser.add_argument("--phase", help="Micro-phase")
    task_parser.add_argument("--project", default="default", help="Project ID")

    # tasks (plural — runtime task management)
    tasks_parser = subparsers.add_parser("tasks", help="Task runtime management commands")
    tasks_subparsers = tasks_parser.add_subparsers(dest="tasks_command")

    tasks_create_parser = tasks_subparsers.add_parser("create", help="Create task from task.yaml")
    tasks_create_parser.add_argument("--file", required=True, help="Path to task.yaml")

    tasks_list_parser = tasks_subparsers.add_parser("list", help="List tasks")
    tasks_list_parser.add_argument("--role", help="Filter by role")
    tasks_list_parser.add_argument(
        "--status",
        choices=["pending", "in_progress", "blocked", "completed", "failed", "archived"],
        help="Filter by status",
    )
    tasks_list_parser.add_argument("--limit", type=int, default=20, help="Limit")

    tasks_show_parser = tasks_subparsers.add_parser("show", help="Show task details")
    tasks_show_parser.add_argument("task_id", help="Task ID")

    tasks_start_parser = tasks_subparsers.add_parser("start", help="Start task")
    tasks_start_parser.add_argument("task_id", help="Task ID")

    tasks_block_parser = tasks_subparsers.add_parser("block", help="Block task")
    tasks_block_parser.add_argument("task_id", help="Task ID")
    tasks_block_parser.add_argument("--reason", default="", help="Block reason")

    tasks_unblock_parser = tasks_subparsers.add_parser("unblock", help="Unblock task")
    tasks_unblock_parser.add_argument("task_id", help="Task ID")

    tasks_complete_parser = tasks_subparsers.add_parser("complete", help="Complete task")
    tasks_complete_parser.add_argument("task_id", help="Task ID")

    tasks_fail_parser = tasks_subparsers.add_parser("fail", help="Fail task")
    tasks_fail_parser.add_argument("task_id", help="Task ID")
    tasks_fail_parser.add_argument("--reason", default="", help="Fail reason")

    tasks_archive_parser = tasks_subparsers.add_parser("archive", help="Archive task")
    tasks_archive_parser.add_argument("task_id", help="Task ID")

    # events
    events_parser = subparsers.add_parser("events", help="Show events")
    events_parser.add_argument("--project", default="default", help="Project ID")
    events_parser.add_argument("--limit", type=int, default=20, help="Limit")

    # sync (Phase 4 Context Builder Lite)
    sync_parser = subparsers.add_parser("sync", help="Context sync commands (Phase 4)")
    sync_subparsers = sync_parser.add_subparsers(dest="sync_command")

    sync_build_parser = sync_subparsers.add_parser("build", help="Build project context")
    sync_build_parser.add_argument(
        "--file",
        action="append",
        dest="files",
        required=True,
        help="Task YAML file (can be specified multiple times)",
    )
    sync_build_parser.add_argument(
        "--output",
        required=True,
        help="Output CONTEXT.json path",
    )
    sync_build_parser.add_argument(
        "--project",
        default="default",
        help="Project ID",
    )

    sync_check_parser = sync_subparsers.add_parser(
        "check", help="Check diffs between YAML and runtime"
    )
    sync_check_parser.add_argument(
        "--file",
        action="append",
        dest="files",
        required=True,
        help="Task YAML file (can be specified multiple times)",
    )

    sync_status_parser = sync_subparsers.add_parser("status", help="Show sync status")
    sync_status_parser.add_argument(
        "--project",
        default="default",
        help="Project ID",
    )

    # approve
    subparsers.add_parser("approve", help="Show pending approvals")

    # evaluate
    evaluate_parser = subparsers.add_parser("evaluate", help="Show improvement summary")
    evaluate_parser.add_argument("--dir", default=".", help="Project directory")
    evaluate_parser.add_argument("--project", default="default", help="Project ID")

    # graph
    graph_parser = subparsers.add_parser("graph", help="LangGraph workflow commands")
    graph_subparsers = graph_parser.add_subparsers(dest="graph_command")

    visualize_parser = graph_subparsers.add_parser("visualize", help="Visualize workflow graph")
    visualize_parser.add_argument(
        "--output",
        default=".voyage/graph.md",
        help="Output path for Mermaid graph",
    )

    graph_run_parser = graph_subparsers.add_parser("run", help="Run agent via LangGraph")
    graph_run_parser.add_argument("role", help="Agent role")
    graph_run_parser.add_argument("--task", default="", help="Task description")
    graph_run_parser.add_argument("--plan", default="", help="Execution plan (semicolon-separated)")
    graph_run_parser.add_argument("--project", default="default", help="Project ID")
    graph_run_parser.add_argument(
        "--correlation-id",
        default=None,
        help="Correlation ID for checkpointing",
    )
    graph_run_parser.add_argument(
        "--backend",
        choices=["subprocess", "docker"],
        default="subprocess",
        help="Sandbox backend (default: subprocess)",
    )
    graph_run_parser.add_argument(
        "--docker-image",
        default="python:3.11-slim",
        help="Docker image when --backend=docker",
    )
    graph_run_parser.add_argument(
        "--feedback",
        action="store_true",
        help="Enable FeedbackLoop",
    )

    graph_state_parser = graph_subparsers.add_parser("state", help="Show graph state")
    graph_state_parser.add_argument("correlation_id", help="Correlation ID")

    # chronicler
    chronicler_parser = subparsers.add_parser("chronicler", help="Chronicler commands")
    chronicler_subparsers = chronicler_parser.add_subparsers(dest="chronicler_command")

    chronicler_journal_parser = chronicler_subparsers.add_parser(
        "journal", help="Show process journal steps"
    )
    chronicler_journal_parser.add_argument("--project", default="default", help="Project ID")
    chronicler_journal_parser.add_argument("--correlation-id", help="Correlation ID")
    chronicler_journal_parser.add_argument("--step-type", help="Filter by step type")
    chronicler_journal_parser.add_argument("--limit", type=int, default=10, help="Limit")

    chronicler_replay_parser = chronicler_subparsers.add_parser(
        "replay", help="Generate replay script"
    )
    chronicler_replay_parser.add_argument("correlation_id", help="Correlation ID")
    chronicler_replay_parser.add_argument("--project", default="default", help="Project ID")
    chronicler_replay_parser.add_argument(
        "--output",
        help="Output path (default: .voyage/replay_<id>.sh)",
    )

    chronicler_decisions_parser = chronicler_subparsers.add_parser(
        "decisions", help="Show decision log"
    )
    chronicler_decisions_parser.add_argument("--project", default="default", help="Project ID")

    chronicler_tutorial_parser = chronicler_subparsers.add_parser(
        "tutorial", help="Generate tutorial draft"
    )
    chronicler_tutorial_parser.add_argument("correlation_id", help="Correlation ID")
    chronicler_tutorial_parser.add_argument("--project", default="default", help="Project ID")
    chronicler_tutorial_parser.add_argument("--output", help="Output path")

    # docs
    docs_parser = subparsers.add_parser("docs", help="Documentation commands")
    docs_subparsers = docs_parser.add_subparsers(dest="docs_command")

    docs_build_parser = docs_subparsers.add_parser("build", help="Build all documentation")
    docs_build_parser.add_argument("--project", default="default", help="Project ID")
    docs_build_parser.add_argument("--output", default="docs", help="Output directory")

    docs_tutorial_parser = docs_subparsers.add_parser("tutorial", help="Generate one tutorial file")
    docs_tutorial_parser.add_argument("correlation_id", help="Correlation ID")
    docs_tutorial_parser.add_argument("--project", default="default", help="Project ID")
    docs_tutorial_parser.add_argument(
        "--output",
        default="docs",
        help="Docs root directory",
    )

    docs_example_parser = docs_subparsers.add_parser("example", help="Generate example directory")
    docs_example_parser.add_argument("correlation_id", help="Correlation ID")
    docs_example_parser.add_argument("--name", required=True, help="Example name")
    docs_example_parser.add_argument("--project", default="default", help="Project ID")
    docs_example_parser.add_argument(
        "--output",
        default="docs/examples",
        help="Examples output directory",
    )

    docs_serve_parser = docs_subparsers.add_parser(
        "serve", help="Serve docs locally with http.server"
    )
    docs_serve_parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to serve on",
    )
    docs_serve_parser.add_argument(
        "--dir",
        default="docs",
        help="Directory to serve",
    )

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    commands: dict[str, Callable[[argparse.Namespace], int]] = {
        "init": init_project,
        "status": show_status,
        "run": lambda a: asyncio.run(run_agent(a)),
        "task": generate_task,
        "tasks": _dispatch_tasks,
        "events": show_events,
        "sync": _dispatch_sync,
        "approve": show_approvals,
        "evaluate": evaluate_project,
        "graph": _dispatch_graph,
        "chronicler": _dispatch_chronicler,
        "docs": _dispatch_docs,
    }

    command_name: str = args.command
    handler = commands.get(command_name)
    if handler is None:
        parser.print_help()
        return 1
    return handler(args)


if __name__ == "__main__":
    sys.exit(main())
