"""CLI для Voyage Framework.

Команды:
    voyage init          — инициализировать проект
    voyage status        — статус проекта
    voyage run <role>    — запустить агента с ролью
    voyage task <role> <task> — сгенерировать TASK.md
    voyage events        — показать последние события
    voyage approve       — показать pending approval запросы
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

from voyage_framework.agents.runtime import AgentRuntime
from voyage_framework.core.event_engine import EventEngine
from voyage_framework.core.models import SecurityPolicy
from voyage_framework.security.policy import PolicyEnforcer
from voyage_framework.security.sandbox import SecureExecutor
from voyage_framework.specs.task_generator import TaskGenerator


def init_project(args: argparse.Namespace) -> int:
    """Инициализировать проект Voyage."""
    project_dir = Path(args.dir)
    voyage_dir = project_dir / ".voyage"
    voyage_dir.mkdir(parents=True, exist_ok=True)

    # Создать базовые файлы
    (voyage_dir / "events.db").touch()
    (voyage_dir / "events.jsonl").touch()
    (voyage_dir / "audit.jsonl").touch()

    # README
    readme = project_dir / "README.md"
    if not readme.exists():
        readme.write_text("""# Voyage Project

Generated by Voyage Framework v4.0

## Quick Start

```bash
voyage run developer --task "Implement feature X"
voyage task developer --task "Refactor module Y"
```
""", encoding="utf-8")

    print(f"✅ Project initialized in {project_dir.absolute()}")
    print(f"   Events DB: {voyage_dir / 'events.db'}")
    print(f"   Audit Log: {voyage_dir / 'audit.jsonl'}")
    return 0


def show_status(args: argparse.Namespace) -> int:
    """Показать статус проекта."""
    engine = EventEngine()
    count = engine.count()
    print(f"📊 Total events: {count}")

    # Последние события
    events = engine.get_events(limit=5)
    if events:
        print("\n📝 Last events:")
        for ev in events:
            ts = ev.timestamp.strftime('%H:%M:%S')
            print(f"   [{ts}] {ev.event_type.value} | {ev.project_id}")
    else:
        print("\n📝 No events yet. Run 'voyage run' to start.")

    return 0


async def run_agent(args: argparse.Namespace) -> int:
    """Запустить агента."""
    engine = EventEngine()
    policy = PolicyEnforcer()
    security = SecurityPolicy()
    executor = SecureExecutor(security)
    runtime = AgentRuntime(engine, executor, policy)

    role = args.role
    task = args.task or "No task specified"
    plan = args.plan.split(";") if args.plan else [task]

    print(f"🚀 Starting agent: role={role}, task={task}")
    result = await runtime.run(
        role=role,
        task=task,
        plan=plan,
        project_id=args.project or "default",
    )

    if result.success:
        print(f"✅ Agent completed. Confidence: {result.state.confidence:.2f}")
    else:
        print(f"❌ Agent failed. Status: {result.state.status.value}")
        if result.output.get("error"):
            print(f"   Error: {result.output['error']}")

    return 0 if result.success else 1


def generate_task(args: argparse.Namespace) -> int:
    """Сгенерировать TASK.md + CONTEXT.json."""
    engine = EventEngine()
    generator = TaskGenerator(engine)

    spec = generator.generate(
        role=args.role,
        task=args.task,
        micro_phase=args.phase,
        project_id=args.project or "default",
    )

    task_path, context_path = generator.write_task_files(spec)

    print("✅ Task generated:")
    print(f"   TASK.md:      {task_path.absolute()}")
    print(f"   CONTEXT.json: {context_path.absolute()}")
    print(f"   Task ID:      {spec.task_id}")
    return 0


def show_events(args: argparse.Namespace) -> int:
    """Показать события."""
    engine = EventEngine()
    events = engine.get_events(
        project_id=args.project,
        limit=args.limit,
    )

    print(f"📊 Events (limit={args.limit}):")
    for ev in events:
        ts = ev.timestamp.strftime('%Y-%m-%d %H:%M:%S')
        print(f"   {ev.event_id[:8]} | {ev.event_type.value:25} | {ts} | {ev.project_id}")

    return 0


def show_approvals(args: argparse.Namespace) -> int:
    """Показать pending approval запросы."""
    from voyage_framework.security.approval import ApprovalQueue

    queue = ApprovalQueue()
    queue.cleanup_expired()
    pending = queue.get_pending()

    if not pending:
        print("✅ No pending approvals")
        return 0

    print(f"⏳ Pending approvals ({len(pending)}):")
    for req in pending:
        ts = req.timestamp.strftime('%H:%M:%S')
        cmd = ' '.join(req.command[:3])
        print(f"   {req.request_id[:8]} | {cmd}... | {req.role} | {ts}")

    return 0


def evaluate_project(args: argparse.Namespace) -> int:
    """Показать evaluation summary проекта."""
    from voyage_framework.core.event_engine import EventEngine
    from voyage_framework.improvement.evaluator import Evaluator
    from voyage_framework.improvement.feedback_loop import FeedbackLoop
    from voyage_framework.improvement.golden_dataset import GoldenDataset
    from voyage_framework.improvement.rule_engine import RuleEngine

    engine = EventEngine()
    evaluator = Evaluator(project_root=Path(args.dir))
    rule_engine = RuleEngine(engine=engine)
    golden_dataset = GoldenDataset(engine=engine)
    feedback = FeedbackLoop(engine, evaluator, rule_engine, golden_dataset)

    summary = feedback.get_improvement_summary(project_id=args.project)

    print(f"📊 Improvement summary for project '{args.project}':")
    print(f"   Evaluations: {summary['evaluations_count']}")
    print(f"   Rules suggested: {summary['rules_suggested_count']}")
    print(f"   Golden matches: {summary['golden_matches_count']}")
    print(f"   Average score: {summary['average_score']:.2f}")
    print(f"   Last score: {summary['last_score']}")
    print(f"   Stored rules: {summary['stored_rules_count']}")
    print(f"   Golden solutions: {summary['golden_solutions_count']}")

    return 0


def main() -> int:
    """Точка входа CLI."""
    # Гарантировать UTF-8 для stdout/stderr на Windows
    if sys.platform == "win32":
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        prog="voyage",
        description="Voyage AI Dev Framework v4.0",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Initialize project")
    init_parser.add_argument("--dir", default=".", help="Project directory")

    # status
    subparsers.add_parser("status", help="Show project status")

    # run
    run_parser = subparsers.add_parser("run", help="Run agent")
    run_parser.add_argument("role", help="Agent role")
    run_parser.add_argument("--task", default="", help="Task description")
    run_parser.add_argument("--plan", default="", help="Execution plan (semicolon-separated)")
    run_parser.add_argument("--project", default="default", help="Project ID")

    # task
    task_parser = subparsers.add_parser("task", help="Generate TASK.md")
    task_parser.add_argument("role", help="Agent role")
    task_parser.add_argument("--task", required=True, help="Task description")
    task_parser.add_argument("--phase", help="Micro-phase")
    task_parser.add_argument("--project", default="default", help="Project ID")

    # events
    events_parser = subparsers.add_parser("events", help="Show events")
    events_parser.add_argument("--project", default="default", help="Project ID")
    events_parser.add_argument("--limit", type=int, default=20, help="Limit")

    # approve
    subparsers.add_parser("approve", help="Show pending approvals")

    # evaluate
    evaluate_parser = subparsers.add_parser("evaluate", help="Show improvement summary")
    evaluate_parser.add_argument("--dir", default=".", help="Project directory")
    evaluate_parser.add_argument("--project", default="default", help="Project ID")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    commands = {
        "init": init_project,
        "status": show_status,
        "run": lambda a: asyncio.run(run_agent(a)),
        "task": generate_task,
        "events": show_events,
        "approve": show_approvals,
        "evaluate": evaluate_project,
    }

    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
